# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(324, 371)
        MainWindow.setMinimumSize(QtCore.QSize(324, 371))
        MainWindow.setMaximumSize(QtCore.QSize(324, 371))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(39, 210, 251, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.error_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.error_label.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(170, 0, 0);")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.horizontalLayout_4.addWidget(self.error_label)
        spacerItem1 = QtWidgets.QSpacerItem(234, 75, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(34, 40, 261, 161))
        self.groupBox.setStyleSheet("\n"
"    background-color: rgb(232,232,232);\n"
"    border-radius: 5px;\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("font: 75 12pt \"Calibri\";\n"
"")
        self.login_label.setObjectName("login_label")
        self.verticalLayout.addWidget(self.login_label)
        self.login_input = QtWidgets.QLineEdit(self.groupBox)
        self.login_input.setStyleSheet("\n"
"font: 10pt \"Calibri\";\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(0,0,0);\n"
"    \n"
"border-top-color: transparent;\n"
"border-left-color: transparent;\n"
"border-right-color: transparent;\n"
"border-radius: 0px;\n"
"")
        self.login_input.setObjectName("login_input")
        self.verticalLayout.addWidget(self.login_input)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.password_label = QtWidgets.QLabel(self.groupBox)
        self.password_label.setStyleSheet("font: 75 12pt \"Calibri\";")
        self.password_label.setObjectName("password_label")
        self.verticalLayout_2.addWidget(self.password_label)
        self.password_input = QtWidgets.QLineEdit(self.groupBox)
        self.password_input.setStyleSheet("font: 10pt \"Calibri\";\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(0,0,0);\n"
"    \n"
"border-top-color: transparent;\n"
"border-left-color: transparent;\n"
"border-right-color: transparent;\n"
"border-radius: 0px;")
        self.password_input.setObjectName("password_input")
        self.verticalLayout_2.addWidget(self.password_input)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 290, 301, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.enter_button = QtWidgets.QPushButton(self.layoutWidget)
        self.enter_button.setMinimumSize(QtCore.QSize(130, 30))
        self.enter_button.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(85, 0, 127);\n"
"    font: 10pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(133, 0, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(163, 0, 245);\n"
"}")
        self.enter_button.setObjectName("enter_button")
        self.horizontalLayout_2.addWidget(self.enter_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_label.setText(_translate("MainWindow", "Имя пользователя (почта)"))
        self.password_label.setText(_translate("MainWindow", "Пароль"))
        self.enter_button.setText(_translate("MainWindow", "Войти"))
import resources_rc
