# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 517)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(77, 0, 116);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 400))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.remote_control_tab = QtWidgets.QWidget()
        self.remote_control_tab.setMinimumSize(QtCore.QSize(250, 400))
        self.remote_control_tab.setObjectName("remote_control_tab")
        self.layoutWidget = QtWidgets.QWidget(self.remote_control_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 737, 209))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.user_groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.user_groupBox.setMinimumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.user_groupBox.setFont(font)
        self.user_groupBox.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.user_groupBox.setTitle("")
        self.user_groupBox.setObjectName("user_groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.user_groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.myid_label = QtWidgets.QLabel(self.user_groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.myid_label.setFont(font)
        self.myid_label.setStyleSheet("background-color: transparent;")
        self.myid_label.setObjectName("myid_label")
        self.verticalLayout.addWidget(self.myid_label)
        self.myid_input = QtWidgets.QLabel(self.user_groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.myid_input.setFont(font)
        self.myid_input.setStyleSheet("background-color: transparent;")
        self.myid_input.setObjectName("myid_input")
        self.verticalLayout.addWidget(self.myid_input)
        self.mypassword_label = QtWidgets.QLabel(self.user_groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mypassword_label.setFont(font)
        self.mypassword_label.setStyleSheet("background-color: transparent;")
        self.mypassword_label.setObjectName("mypassword_label")
        self.verticalLayout.addWidget(self.mypassword_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mypassword_input = QtWidgets.QLabel(self.user_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mypassword_input.setFont(font)
        self.mypassword_input.setStyleSheet("background-color: transparent;")
        self.mypassword_input.setObjectName("mypassword_input")
        self.horizontalLayout_3.addWidget(self.mypassword_input)
        self.change_password_button = QtWidgets.QPushButton(self.user_groupBox)
        self.change_password_button.setMinimumSize(QtCore.QSize(10, 10))
        self.change_password_button.setMaximumSize(QtCore.QSize(50, 200))
        self.change_password_button.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(245, 245, 245);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(250, 250, 250);\n"
"}")
        self.change_password_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_password_button.setIcon(icon)
        self.change_password_button.setIconSize(QtCore.QSize(16, 16))
        self.change_password_button.setObjectName("change_password_button")
        self.horizontalLayout_3.addWidget(self.change_password_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.user_groupBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.user_groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.user_groupBox_2.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.user_groupBox_2.setFont(font)
        self.user_groupBox_2.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"}")
        self.user_groupBox_2.setTitle("")
        self.user_groupBox_2.setObjectName("user_groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.user_groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.control_type_comboBox = QtWidgets.QComboBox(self.user_groupBox_2)
        self.control_type_comboBox.setMinimumSize(QtCore.QSize(100, 20))
        self.control_type_comboBox.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.control_type_comboBox.setFont(font)
        self.control_type_comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.control_type_comboBox.setAutoFillBackground(False)
        self.control_type_comboBox.setStyleSheet("QComboBox{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.control_type_comboBox.setCurrentText("Удаленное управление")
        self.control_type_comboBox.setObjectName("control_type_comboBox")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/exchange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.control_type_comboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.control_type_comboBox.addItem(icon2, "")
        self.verticalLayout_5.addWidget(self.control_type_comboBox)
        self.remote_id_input = QtWidgets.QLineEdit(self.user_groupBox_2)
        self.remote_id_input.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.remote_id_input.setFont(font)
        self.remote_id_input.setObjectName("remote_id_input")
        self.verticalLayout_5.addWidget(self.remote_id_input)
        self.remote_password_input = QtWidgets.QLineEdit(self.user_groupBox_2)
        self.remote_password_input.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.remote_password_input.setFont(font)
        self.remote_password_input.setObjectName("remote_password_input")
        self.verticalLayout_5.addWidget(self.remote_password_input)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem1)
        self.remote_connect_button = QtWidgets.QPushButton(self.user_groupBox_2)
        self.remote_connect_button.setMinimumSize(QtCore.QSize(130, 30))
        self.remote_connect_button.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.remote_connect_button.setFont(font)
        self.remote_connect_button.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(85, 0, 127);\n"
"    font: 12pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(133, 0, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(163, 0, 245);\n"
"}")
        self.remote_connect_button.setObjectName("remote_connect_button")
        self.verticalLayout_5.addWidget(self.remote_connect_button)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.user_groupBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.remote_control_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 390, 741, 52))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.server_connect_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.server_connect_button.setMinimumSize(QtCore.QSize(75, 25))
        self.server_connect_button.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(85, 0, 127);\n"
"    font: 12pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(133, 0, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(163, 0, 245);\n"
"}")
        self.server_connect_button.setObjectName("server_connect_button")
        self.horizontalLayout_8.addWidget(self.server_connect_button)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/remote_control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.remote_control_tab, icon3, "")
        self.metting_tab = QtWidgets.QWidget()
        self.metting_tab.setMinimumSize(QtCore.QSize(250, 500))
        self.metting_tab.setObjectName("metting_tab")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/meeting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.metting_tab, icon4, "")
        self.requests_tab = QtWidgets.QWidget()
        self.requests_tab.setObjectName("requests_tab")
        self.layoutWidget1 = QtWidgets.QWidget(self.requests_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 511, 391))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.refresh_requests_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.refresh_requests_button.setMaximumSize(QtCore.QSize(50, 50))
        self.refresh_requests_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_requests_button.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(250, 250, 250);\n"
"}")
        self.refresh_requests_button.setText("")
        self.refresh_requests_button.setIcon(icon)
        self.refresh_requests_button.setObjectName("refresh_requests_button")
        self.horizontalLayout_7.addWidget(self.refresh_requests_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.requests_table = QtWidgets.QTableWidget(self.layoutWidget1)
        self.requests_table.setMaximumSize(QtCore.QSize(749, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.requests_table.setFont(font)
        self.requests_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.requests_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.requests_table.setAlternatingRowColors(True)
        self.requests_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.requests_table.setObjectName("requests_table")
        self.requests_table.setColumnCount(3)
        self.requests_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.requests_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.requests_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.requests_table.setHorizontalHeaderItem(2, item)
        self.requests_table.horizontalHeader().setCascadingSectionResizes(False)
        self.requests_table.horizontalHeader().setDefaultSectionSize(160)
        self.verticalLayout_6.addWidget(self.requests_table)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/globe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.requests_tab, icon5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Подключиться ко мне"))
        self.myid_label.setText(_translate("MainWindow", "Мой ID"))
        self.myid_input.setText(_translate("MainWindow", "ID"))
        self.mypassword_label.setText(_translate("MainWindow", "Пароль"))
        self.mypassword_input.setText(_translate("MainWindow", "password"))
        self.change_password_button.setToolTip(_translate("MainWindow", "Создать новый случайный пароль"))
        self.label_2.setText(_translate("MainWindow", "Управлять удаленным компьютером"))
        self.control_type_comboBox.setItemText(0, _translate("MainWindow", "Удаленное управление"))
        self.control_type_comboBox.setItemText(1, _translate("MainWindow", "Передача файлов"))
        self.remote_id_input.setPlaceholderText(_translate("MainWindow", "Введите ID Партнера"))
        self.remote_password_input.setPlaceholderText(_translate("MainWindow", "Введите пароль Партнера"))
        self.remote_connect_button.setText(_translate("MainWindow", "Cоединиться"))
        self.server_connect_button.setText(_translate("MainWindow", "Сессия"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.remote_control_tab), _translate("MainWindow", "Удаленное управление"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.metting_tab), _translate("MainWindow", "Собрание"))
        self.label_3.setText(_translate("MainWindow", "Текущие подключения"))
        self.refresh_requests_button.setToolTip(_translate("MainWindow", "Обновить список активных подключений"))
        self.requests_table.setSortingEnabled(True)
        item = self.requests_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Пользователь"))
        item = self.requests_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Статус"))
        item = self.requests_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Действия"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.requests_tab), _translate("MainWindow", "Подключения"))
import resources_rc
